"""empty message

Revision ID: 1564d04b553d
Revises: 
Create Date: 2019-07-08 05:50:05.141378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1564d04b553d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_utc', sa.DateTime(), nullable=False),
    sa.Column('modified_utc', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_utc', sa.DateTime(), nullable=False),
    sa.Column('modified_utc', sa.DateTime(), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('password', sa.Binary(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('hands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_utc', sa.DateTime(), nullable=False),
    sa.Column('modified_utc', sa.DateTime(), nullable=False),
    sa.Column('board', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('dealer_id', sa.Integer(), nullable=False),
    sa.Column('dealer_pos', sa.Integer(), nullable=False),
    sa.Column('next_to_act_id', sa.Integer(), nullable=False),
    sa.Column('next_to_act_pos', sa.Integer(), nullable=False),
    sa.Column('pot_pennies', sa.Integer(), nullable=False),
    sa.Column('in_progress', sa.Boolean(), nullable=False),
    sa.Column('current_bet', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dealer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['next_to_act_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_utc', sa.DateTime(), nullable=False),
    sa.Column('modified_utc', sa.DateTime(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('holdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_utc', sa.DateTime(), nullable=False),
    sa.Column('modified_utc', sa.DateTime(), nullable=False),
    sa.Column('cards', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('hand_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('in_progress', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['hand_id'], ['hands.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_utc', sa.DateTime(), nullable=False),
    sa.Column('modified_utc', sa.DateTime(), nullable=False),
    sa.Column('hand_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('holding_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.Enum('BLIND', 'FOLD', 'CHECK', 'BET', name='actiontype'), nullable=False),
    sa.ForeignKeyConstraint(['hand_id'], ['hands.id'], ),
    sa.ForeignKeyConstraint(['holding_id'], ['holdings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('actions')
    op.drop_table('holdings')
    op.drop_table('players')
    op.drop_table('hands')
    op.drop_table('users')
    op.drop_table('tables')
    # ### end Alembic commands ###
