"""empty message

Revision ID: 2869adbeccd6
Revises: f25bf10a3e5d
Create Date: 2019-06-22 14:38:19.657069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2869adbeccd6'
down_revision = 'f25bf10a3e5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_utc', sa.DateTime(), nullable=False),
    sa.Column('modified_utc', sa.DateTime(), nullable=False),
    sa.Column('board', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('holdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_utc', sa.DateTime(), nullable=False),
    sa.Column('modified_utc', sa.DateTime(), nullable=False),
    sa.Column('cards', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('hand_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hand_id'], ['hands.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('holdings')
    op.drop_table('hands')
    # ### end Alembic commands ###
