"""empty message

Revision ID: 47f1a9d0b1ee
Revises: 2869adbeccd6
Create Date: 2019-06-26 05:10:27.905843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47f1a9d0b1ee'
down_revision = '2869adbeccd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('table_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'tables', ['table_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'table_id')
    # ### end Alembic commands ###
