"""Remove unique table-seat constraint

Revision ID: 575bbda7efa1
Revises: 828c2c5fbc25
Create Date: 2019-07-28 06:59:33.326068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '575bbda7efa1'
down_revision = '828c2c5fbc25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_table_seat', 'players', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_table_seat', 'players', ['table_id', 'seat'])
    # ### end Alembic commands ###
