"""Add blind leading flag

Revision ID: 62d481587cdb
Revises: 48992f94caca
Create Date: 2019-10-29 05:20:21.228191

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import orm
from sqlalchemy.ext.declarative import declarative_base
from models import BettingRound


# revision identifiers, used by Alembic.
revision = '62d481587cdb'
down_revision = '48992f94caca'
branch_labels = None
depends_on = None

Base = declarative_base()


def upgrade():
    bind = op.get_bind()
    session = orm.Session(bind=bind)
    op.add_column('betting_rounds', sa.Column('blind_leading', sa.Boolean(), nullable=True))

    for round in session.query(BettingRound):
        round.blind_leading = False
    session.commit()

    op.alter_column('betting_rounds', 'blind_leading', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('betting_rounds', 'blind_leading')
    # ### end Alembic commands ###
