"""empty message

Revision ID: 6645639c1c99
Revises: ace422496688
Create Date: 2019-06-27 13:32:48.963290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6645639c1c99'
down_revision = 'ace422496688'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hands', sa.Column('in_progress', sa.Boolean(), server_default='False', nullable=False))
    # ### end Alembic commands ###

    # Custom added by Matt
    op.alter_column('hands', 'in_progress', server_default=None)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hands', 'in_progress')
    # ### end Alembic commands ###
