"""add-table-id-to-players-active

Revision ID: 74f799a89f3b
Revises: 7937450b56bd
Create Date: 2019-07-27 06:14:36.310388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74f799a89f3b'
down_revision = '7937450b56bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players_active', sa.Column('table_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'players_active', 'tables', ['table_id'], ['id'])
    op.drop_column('players_active', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players_active', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'players_active', type_='foreignkey')
    op.drop_column('players_active', 'table_id')
    # ### end Alembic commands ###
