"""empty message

Revision ID: 76feb0ca6889
Revises: bbfb7d409749
Create Date: 2019-06-29 06:34:41.638467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76feb0ca6889'
down_revision = 'bbfb7d409749'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hands', sa.Column('dealer_id', sa.Integer(), nullable=False))
    op.add_column('hands', sa.Column('next_to_act_id', sa.Integer(), nullable=False))
    op.add_column('hands', sa.Column('next_to_act_pos', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'hands', 'users', ['next_to_act'], ['id'])
    op.create_foreign_key(None, 'hands', 'users', ['dealer_id'], ['id'])
    op.drop_column('hands', 'next_pos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hands', sa.Column('next_pos', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'hands', type_='foreignkey')
    op.drop_constraint(None, 'hands', type_='foreignkey')
    op.drop_column('hands', 'next_to_act_pos')
    op.drop_column('hands', 'next_to_act')
    op.drop_column('hands', 'dealer_id')
    # ### end Alembic commands ###
