"""Remove table ID from players_active

Revision ID: 828c2c5fbc25
Revises: cf8cede093dc
Create Date: 2019-07-28 05:39:59.813654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '828c2c5fbc25'
down_revision = 'cf8cede093dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('players_active_table_id_fkey', 'players_active', type_='foreignkey')
    op.drop_column('players_active', 'table_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players_active', sa.Column('table_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('players_active_table_id_fkey', 'players_active', 'tables', ['table_id'], ['id'])
    # ### end Alembic commands ###
