"""Add SSEChannel model

Revision ID: 8eb8a3ac7bf7
Revises: 0d93e6c0e637
Create Date: 2019-09-06 05:53:54.975879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8eb8a3ac7bf7'
down_revision = '0d93e6c0e637'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sse_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sse_id', sa.Integer(), nullable=False),
    sa.Column('created_utc', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sse_channels')
    # ### end Alembic commands ###
