"""empty message

Revision ID: ace422496688
Revises: 47f1a9d0b1ee
Create Date: 2019-06-26 12:51:40.277601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ace422496688'
down_revision = '47f1a9d0b1ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_utc', sa.DateTime(), nullable=False),
    sa.Column('modified_utc', sa.DateTime(), nullable=False),
    sa.Column('hand_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('holding_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.Enum('FOLD', 'CALL', 'RAISE', 'BLIND', name='actiontypes'), nullable=False),
    sa.ForeignKeyConstraint(['hand_id'], ['hands.id'], ),
    sa.ForeignKeyConstraint(['holding_id'], ['holdings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('hands', sa.Column('dealer_pos', sa.Integer(), nullable=False))
    op.add_column('hands', sa.Column('next_pos', sa.Integer(), nullable=False))
    op.add_column('hands', sa.Column('pot_pennies', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hands', 'pot_pennies')
    op.drop_column('hands', 'next_pos')
    op.drop_column('hands', 'dealer_pos')
    op.drop_table('actions')
    # ### end Alembic commands ###
