"""empty message

Revision ID: af649b440d8f
Revises: 1564d04b553d
Create Date: 2019-07-09 12:36:01.578210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af649b440d8f'
down_revision = '1564d04b553d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hands', sa.Column('lead_bettor_pos', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hands', 'lead_bettor_pos')
    # ### end Alembic commands ###
