"""empty message

Revision ID: bbfb7d409749
Revises: 6645639c1c99
Create Date: 2019-06-29 06:16:45.717328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbfb7d409749'
down_revision = '6645639c1c99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('holdings', sa.Column('in_progress', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('holdings', 'in_progress')
    # ### end Alembic commands ###
