"""Remove IDs on M2M tables

Revision ID: cf8cede093dc
Revises: 74f799a89f3b
Create Date: 2019-07-27 17:36:54.946879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf8cede093dc'
down_revision = '74f799a89f3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('betting_rounds_active', 'id')
    op.drop_column('hands_active', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hands_active', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('betting_rounds_active', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###
