"""empty message

Revision ID: d009134204f7
Revises: af649b440d8f
Create Date: 2019-07-13 06:46:29.730819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd009134204f7'
down_revision = 'af649b440d8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('betting_rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_utc', sa.DateTime(), nullable=False),
    sa.Column('modified_utc', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('hand_id', sa.Integer(), nullable=False),
    sa.Column('in_progress', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['hand_id'], ['hands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_utc', sa.DateTime(), nullable=False),
    sa.Column('modified_utc', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('betting_round_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['betting_round_id'], ['betting_rounds.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('hands', sa.Column('current_round_id', sa.Integer(), nullable=False))
    op.add_column('hands', sa.Column('rounds', sa.ARRAY(sa.String()), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hands', 'rounds')
    op.drop_column('hands', 'current_round_id')
    op.drop_table('bets')
    op.drop_table('betting_rounds')
    # ### end Alembic commands ###
