"""Allow null betting_round.bettor_id

Revision ID: d035812ab87f
Revises: 575bbda7efa1
Create Date: 2019-07-29 12:08:12.467460

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd035812ab87f'
down_revision = '575bbda7efa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('betting_rounds', sa.Column('bettor_id', sa.Integer(), nullable=True))
    op.alter_column('betting_rounds', 'state',
               existing_type=postgresql.ENUM('VOID', 'CLOSED', 'OPEN', name='state'),
               nullable=False)
    op.drop_constraint('betting_rounds_bettor_fkey', 'betting_rounds', type_='foreignkey')
    op.create_foreign_key(None, 'betting_rounds', 'players', ['bettor_id'], ['id'])
    op.drop_column('betting_rounds', 'name')
    op.drop_column('betting_rounds', 'bettor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('betting_rounds', sa.Column('bettor', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('betting_rounds', sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'betting_rounds', type_='foreignkey')
    op.create_foreign_key('betting_rounds_bettor_fkey', 'betting_rounds', 'players', ['bettor'], ['id'])
    op.alter_column('betting_rounds', 'state',
               existing_type=postgresql.ENUM('VOID', 'CLOSED', 'OPEN', name='state'),
               nullable=True)
    op.drop_column('betting_rounds', 'bettor_id')
    # ### end Alembic commands ###
