"""Add pots to players m2m table

Revision ID: f0bbcc4ae914
Revises: 20cd0eb1e1bf
Create Date: 2019-10-05 05:51:52.926209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0bbcc4ae914'
down_revision = '20cd0eb1e1bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pots_players',
    sa.Column('pot_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['pot_id'], ['pots.id'], ),
    sa.PrimaryKeyConstraint('pot_id', 'player_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pots_players')
    # ### end Alembic commands ###
