"""empty message

Revision ID: f691692933cf
Revises: 23bb155962a2
Create Date: 2019-07-01 06:00:26.320781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f691692933cf'
down_revision = '23bb155962a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('position', sa.Integer(), nullable=False))
    op.add_column('players', sa.Column('table_id', sa.Integer(), nullable=False))
    op.add_column('players', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'players', ['user_id'])
    op.create_foreign_key(None, 'players', 'tables', ['table_id'], ['id'])
    op.create_foreign_key(None, 'players', 'users', ['user_id'], ['id'])
    op.drop_column('players', 'name')
    op.add_column('tables', sa.Column('seats', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tables', 'seats')
    op.add_column('players', sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'players', type_='foreignkey')
    op.drop_constraint(None, 'players', type_='foreignkey')
    op.drop_constraint(None, 'players', type_='unique')
    op.drop_column('players', 'user_id')
    op.drop_column('players', 'table_id')
    op.drop_column('players', 'position')
    # ### end Alembic commands ###
